##########################
# @author Amit Gera <er.amitgera@gmail.com>
##########################
# [START]
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: gerua-frontend-canary
  namespace: devops
spec:
  replicas: 1
  template:
    metadata:
      name: frontend
      labels:
        app: gerua
        role: frontend
        env: canary
    spec:
      containers:
      - name: frontend
        image: docker-registry/gerua:1.0.0
        resources:
          limits:
            memory: "300Mi"
            cpu: "100m"
        imagePullPolicy: Always
        readinessProbe:
          httpGet:
            path: /healthz
            port: 80
        command: ["sh", "-c", "app -port=80"]
        ports:
        - name: frontend
          containerPort: 80
      imagePullSecrets:
      - name: devops-k8s-ap-southeast-1-ecr-registry
# [END]
