kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: gerua-frontend-production
  namespace: devops
spec:
  replicas: 2
  template:
    metadata:
      name: frontend
      labels:
        app: gerua
        role: frontend
        env: production
    spec:
      containers:
      - name: frontend
        image: docker-registry/gerua:1.0.0
        resources:
          limits:
            memory: "300Mi"
            cpu: "100m"
        imagePullPolicy: Always
        readinessProbe:
          httpGet:
            path: /healthz
            port: 80
        command: ["sh", "-c", "app -port=80"]
        ports:
        - name: frontend
          containerPort: 80
