##########################
# @author Amit Gera <er.amitgera@gmail.com>
##########################
# [START]
kind: Service
apiVersion: v1
metadata:
  name: gerua-frontend
  namespace: devops
  annotations:
        service.beta.kubernetes.io/aws-load-balancer-internal: 0.0.0.0/0
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: gerua
    role: frontend
# [END]